dev:
  app_name: "code_sim"
  host: "0.0.0.0"
  port: 4401
  consul_addr: "http://133.133.135.42:8500"
  es_addr: "http://133.133.135.42:9200"
  transform_code_splitter: "`/"
  network_interface: "eth2"

prd:
  app_name: "code_sim"
  host: "0.0.0.0" # for test
  port: 4401
  consul_addr: "http://consul_server:8500"
  es_addr: "http://es:9200"
  transform_code_splitter: "`/"
  network_interface: "eth2"