dev:
  app_name: "code_sim"
  host: "0.0.0.0"
  port: 4401
  es_addr: "http://es:9200"
  transform_code_splitter: "`/"
  python_lexical_analyzer_path: "/Users/purchaser/go/src/code_sim/transformer/python-lexical-analyzer/analyze.py"

prd:
  app_name: "code_sim"
  host: "0.0.0.0" # for test
  port: 4401
  es_addr: "http://es:9200"
  transform_code_splitter: "`/"
  python_lexical_analyzer_path: "/Users/purchaser/go/src/code_sim/transformer/python-lexical-analyzer/analyze.py"