// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.5.0
// source: code_sim/code_sim_service.proto

package pb_gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CodeSimSearchRequest_CodeType int32

const (
	CodeSimSearchRequest_python CodeSimSearchRequest_CodeType = 0
)

// Enum value maps for CodeSimSearchRequest_CodeType.
var (
	CodeSimSearchRequest_CodeType_name = map[int32]string{
		0: "python",
	}
	CodeSimSearchRequest_CodeType_value = map[string]int32{
		"python": 0,
	}
)

func (x CodeSimSearchRequest_CodeType) Enum() *CodeSimSearchRequest_CodeType {
	p := new(CodeSimSearchRequest_CodeType)
	*p = x
	return p
}

func (x CodeSimSearchRequest_CodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CodeSimSearchRequest_CodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_code_sim_code_sim_service_proto_enumTypes[0].Descriptor()
}

func (CodeSimSearchRequest_CodeType) Type() protoreflect.EnumType {
	return &file_code_sim_code_sim_service_proto_enumTypes[0]
}

func (x CodeSimSearchRequest_CodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CodeSimSearchRequest_CodeType.Descriptor instead.
func (CodeSimSearchRequest_CodeType) EnumDescriptor() ([]byte, []int) {
	return file_code_sim_code_sim_service_proto_rawDescGZIP(), []int{2, 0}
}

type CodeSimHelloWorldRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HelloText string `protobuf:"bytes,1,opt,name=hello_text,json=helloText,proto3" json:"hello_text,omitempty"`
}

func (x *CodeSimHelloWorldRequest) Reset() {
	*x = CodeSimHelloWorldRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_sim_code_sim_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeSimHelloWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeSimHelloWorldRequest) ProtoMessage() {}

func (x *CodeSimHelloWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code_sim_code_sim_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeSimHelloWorldRequest.ProtoReflect.Descriptor instead.
func (*CodeSimHelloWorldRequest) Descriptor() ([]byte, []int) {
	return file_code_sim_code_sim_service_proto_rawDescGZIP(), []int{0}
}

func (x *CodeSimHelloWorldRequest) GetHelloText() string {
	if x != nil {
		return x.HelloText
	}
	return ""
}

type CodeSimHelloWorldResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ThanksText string `protobuf:"bytes,1,opt,name=thanks_text,json=thanksText,proto3" json:"thanks_text,omitempty"`
}

func (x *CodeSimHelloWorldResponse) Reset() {
	*x = CodeSimHelloWorldResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_sim_code_sim_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeSimHelloWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeSimHelloWorldResponse) ProtoMessage() {}

func (x *CodeSimHelloWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code_sim_code_sim_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeSimHelloWorldResponse.ProtoReflect.Descriptor instead.
func (*CodeSimHelloWorldResponse) Descriptor() ([]byte, []int) {
	return file_code_sim_code_sim_service_proto_rawDescGZIP(), []int{1}
}

func (x *CodeSimHelloWorldResponse) GetThanksText() string {
	if x != nil {
		return x.ThanksText
	}
	return ""
}

type CodeSimSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MatchText       string                        `protobuf:"bytes,1,opt,name=match_text,json=matchText,proto3" json:"match_text,omitempty"`
	MatchTextIsCode bool                          `protobuf:"varint,2,opt,name=match_text_is_code,json=matchTextIsCode,proto3" json:"match_text_is_code,omitempty"`
	CodeType        CodeSimSearchRequest_CodeType `protobuf:"varint,3,opt,name=code_type,json=codeType,proto3,enum=pb.CodeSimSearchRequest_CodeType" json:"code_type,omitempty"`
	Limit           int32                         `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset          int32                         `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *CodeSimSearchRequest) Reset() {
	*x = CodeSimSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_sim_code_sim_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeSimSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeSimSearchRequest) ProtoMessage() {}

func (x *CodeSimSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_code_sim_code_sim_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeSimSearchRequest.ProtoReflect.Descriptor instead.
func (*CodeSimSearchRequest) Descriptor() ([]byte, []int) {
	return file_code_sim_code_sim_service_proto_rawDescGZIP(), []int{2}
}

func (x *CodeSimSearchRequest) GetMatchText() string {
	if x != nil {
		return x.MatchText
	}
	return ""
}

func (x *CodeSimSearchRequest) GetMatchTextIsCode() bool {
	if x != nil {
		return x.MatchTextIsCode
	}
	return false
}

func (x *CodeSimSearchRequest) GetCodeType() CodeSimSearchRequest_CodeType {
	if x != nil {
		return x.CodeType
	}
	return CodeSimSearchRequest_python
}

func (x *CodeSimSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CodeSimSearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type CodeSimSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileUniquePath []string `protobuf:"bytes,1,rep,name=file_unique_path,json=fileUniquePath,proto3" json:"file_unique_path,omitempty"`
}

func (x *CodeSimSearchResponse) Reset() {
	*x = CodeSimSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_code_sim_code_sim_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CodeSimSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeSimSearchResponse) ProtoMessage() {}

func (x *CodeSimSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_code_sim_code_sim_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeSimSearchResponse.ProtoReflect.Descriptor instead.
func (*CodeSimSearchResponse) Descriptor() ([]byte, []int) {
	return file_code_sim_code_sim_service_proto_rawDescGZIP(), []int{3}
}

func (x *CodeSimSearchResponse) GetFileUniquePath() []string {
	if x != nil {
		return x.FileUniquePath
	}
	return nil
}

var File_code_sim_code_sim_service_proto protoreflect.FileDescriptor

var file_code_sim_code_sim_service_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x73, 0x69, 0x6d, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x5f,
	0x73, 0x69, 0x6d, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x39, 0x0a, 0x18, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x69, 0x6d,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x54, 0x65, 0x78, 0x74,
	0x22, 0x3c, 0x0a, 0x19, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x69, 0x6d, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a,
	0x0b, 0x74, 0x68, 0x61, 0x6e, 0x6b, 0x73, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x74, 0x68, 0x61, 0x6e, 0x6b, 0x73, 0x54, 0x65, 0x78, 0x74, 0x22, 0xe8,
	0x01, 0x0a, 0x14, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x69, 0x6d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x74,
	0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x12, 0x2b, 0x0a, 0x12, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x74, 0x65, 0x78, 0x74, 0x5f, 0x69, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x49, 0x73, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x3e, 0x0a, 0x09, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x64, 0x65,
	0x53, 0x69, 0x6d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x63, 0x6f, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66,
	0x73, 0x65, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x22, 0x16, 0x0a, 0x08, 0x43, 0x6f, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x70, 0x79, 0x74, 0x68, 0x6f, 0x6e, 0x10, 0x00, 0x22, 0x41, 0x0a, 0x15, 0x43, 0x6f, 0x64,
	0x65, 0x53, 0x69, 0x6d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x71, 0x75,
	0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x66, 0x69,
	0x6c, 0x65, 0x55, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x50, 0x61, 0x74, 0x68, 0x32, 0x97, 0x01, 0x0a,
	0x07, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x69, 0x6d, 0x12, 0x4b, 0x0a, 0x0a, 0x48, 0x65, 0x6c, 0x6c,
	0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x64, 0x65,
	0x53, 0x69, 0x6d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x69,
	0x6d, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12,
	0x18, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x64, 0x65, 0x53, 0x69, 0x6d, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x6f, 0x64, 0x65, 0x53, 0x69, 0x6d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x70, 0x62, 0x5f, 0x67,
	0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_code_sim_code_sim_service_proto_rawDescOnce sync.Once
	file_code_sim_code_sim_service_proto_rawDescData = file_code_sim_code_sim_service_proto_rawDesc
)

func file_code_sim_code_sim_service_proto_rawDescGZIP() []byte {
	file_code_sim_code_sim_service_proto_rawDescOnce.Do(func() {
		file_code_sim_code_sim_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_code_sim_code_sim_service_proto_rawDescData)
	})
	return file_code_sim_code_sim_service_proto_rawDescData
}

var file_code_sim_code_sim_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_code_sim_code_sim_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_code_sim_code_sim_service_proto_goTypes = []interface{}{
	(CodeSimSearchRequest_CodeType)(0), // 0: pb.CodeSimSearchRequest.CodeType
	(*CodeSimHelloWorldRequest)(nil),   // 1: pb.CodeSimHelloWorldRequest
	(*CodeSimHelloWorldResponse)(nil),  // 2: pb.CodeSimHelloWorldResponse
	(*CodeSimSearchRequest)(nil),       // 3: pb.CodeSimSearchRequest
	(*CodeSimSearchResponse)(nil),      // 4: pb.CodeSimSearchResponse
}
var file_code_sim_code_sim_service_proto_depIdxs = []int32{
	0, // 0: pb.CodeSimSearchRequest.code_type:type_name -> pb.CodeSimSearchRequest.CodeType
	1, // 1: pb.CodeSim.HelloWorld:input_type -> pb.CodeSimHelloWorldRequest
	3, // 2: pb.CodeSim.Search:input_type -> pb.CodeSimSearchRequest
	2, // 3: pb.CodeSim.HelloWorld:output_type -> pb.CodeSimHelloWorldResponse
	4, // 4: pb.CodeSim.Search:output_type -> pb.CodeSimSearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_code_sim_code_sim_service_proto_init() }
func file_code_sim_code_sim_service_proto_init() {
	if File_code_sim_code_sim_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_code_sim_code_sim_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeSimHelloWorldRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code_sim_code_sim_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeSimHelloWorldResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code_sim_code_sim_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeSimSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_code_sim_code_sim_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CodeSimSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_code_sim_code_sim_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_code_sim_code_sim_service_proto_goTypes,
		DependencyIndexes: file_code_sim_code_sim_service_proto_depIdxs,
		EnumInfos:         file_code_sim_code_sim_service_proto_enumTypes,
		MessageInfos:      file_code_sim_code_sim_service_proto_msgTypes,
	}.Build()
	File_code_sim_code_sim_service_proto = out.File
	file_code_sim_code_sim_service_proto_rawDesc = nil
	file_code_sim_code_sim_service_proto_goTypes = nil
	file_code_sim_code_sim_service_proto_depIdxs = nil
}
